### ISSUE TITLE
Test results for URxvt

### ISSUE THREAD

**Issue by pr3ssh** [Dica-Developer/terminal-benchmark#1]
My laptop:
* CPU: Intel i7-6700HQ (8) @ 3.500GHz
* GPU: NVIDIA GeForce 940MX
* GPU: Intel HD Graphics 530
*  Memory: 5322MiB / 15875MiB
_(extracted using neofetch)_

**URxvt:**

```
Mixed output test takes:  12.943543801  seconds
4425868 coloured characters per second
6709818 unicode characters per second
10327260 none-unicode characters per second
1274766 Mixed characters per second
```

**Alacritty**

```
Mixed output test takes:  15.147634208  seconds
3759325 coloured characters per second
5346162 unicode characters per second
8351920 none-unicode characters per second
1089279 Mixed characters per second
```

**Comment by mschaaf** [comment]
thanks for the data. I put it into the wiki https://github.com/Dica-Developer/terminal-benchmark/wiki/user-test-results
